/* Public projection only: never publish decks, hands, facedown card IDs, seeds or move logs. */
(function(root){'use strict';
const number=(n,max=100000)=>Math.min(max,Math.max(0,Math.floor(Number(n)||0)));
const COINS=['basic','copper','silver','gold','sakura','night','crown','neon','jade','crystal','flame','kmr1','eldorado'];
const cleanCoins=v=>Array.from({length:2},(_,i)=>Array.isArray(v)&&COINS.includes(v[i])?v[i]:'basic');
const card=id=>typeof id==='string'&&/^[wqygivcdnso][1-8]$|^x[1-4]$/.test(id)?id:'';
function cleanPlayer(p){p=p&&typeof p==='object'?p:{};return{life:number(p.life),energy:number(p.energy,20),maxEnergy:number(p.maxEnergy,20),gauge:number(p.gauge,10),skillUsed:!!p.skillUsed,handCount:number(p.handCount,7),deckCount:number(p.deckCount,20),graveCount:number(p.graveCount,200),trapCount:number(p.trapCount,3),trapUids:(Array.isArray(p.trapUids)?p.trapUids:[]).slice(0,3).map(x=>number(x)),leadId:card(p.leadId),leadOut:!!p.leadOut,board:Array.from({length:4},(_,i)=>{const m=p.board&&p.board[i];return m&&card(m.id)?{uid:number(m.uid),underCount:number(m.underCount,20),rush:!!m.rush,awk:!!m.awk,gutsUsed:!!m.gutsUsed,id:card(m.id),atk:number(m.atk),def:number(m.def),star:Math.max(1,number(m.star,3)),sick:!!m.sick,cover:!!m.cover,scr:!!m.scr}:null})}}
function cleanState(s){s=s&&typeof s==='object'?s:{};const players=Array.isArray(s.players)?s.players:[];return{cur:number(s.cur,1),turns:number(s.turns,1000),over:!!s.over,winner:s.over&&[0,1,-1].includes(s.winner)?s.winner:-1,players:[cleanPlayer(players[0]),cleanPlayer(players[1])]}}
function publicState(g,E){return cleanState({cur:g.cur,turns:g.turns,over:g.over,winner:g.win,players:g.p.map(p=>({life:p.life,energy:p.energy,maxEnergy:p.maxE,gauge:p.gauge,skillUsed:p.skillUsed,handCount:p.hand.length,deckCount:p.deck.length,graveCount:p.gy.length,trapCount:p.st.length,trapUids:p.st.map(t=>t.uid),leadId:p.leader.id,leadOut:p.leader.out,board:p.slot.map(m=>m?{uid:m.uid,underCount:m.under.length,rush:m.rush,awk:m.awk,gutsUsed:m.gutsUsed,id:m.id,atk:E.ATK(g,m),def:E.DEF(g,m),star:m.star,sick:m.sick&&!m.rush,cover:E.hasCover(m)}:null)}))})}
// Only events whose card identity is already public are eligible. Never accept arbitrary engine fields.
function cleanEvents(events){const schema={tribute:'who uid id',play:'who uid id slot free scr',spell:'who id scr',stack:'who uid id same',star:'uid from to',awake:'who uid id',set:'who uid',trap:'who uid id scr',negated:'who',atk:'who uid id to kind',direct:'who uid',clash:'a b A D B AD',dmg:'who n',heal:'who n',die:'who uid id star',guts:'uid',coin:'who h',rush:'uid',gauge:'who v',skill:'who k',end:'win why',energy:'who n',revive:'who id',reshuffle:'who'};
 return(Array.isArray(events)?events:[]).slice(0,100).filter(e=>e&&schema[e.t]&&(!schema[e.t].split(' ').includes('id')||card(e.id))&&(e.t!=='skill'||/^(weak|girl|gay|gachi|idol|vt|cre|chu|neta|sei|hage)$/.test(e.k))).map(e=>{const o={t:e.t};for(const k of schema[e.t].split(' ')){if(k==='id'){if(card(e.id))o.id=card(e.id)}else if(k==='k'){if(/^(weak|girl|gay|gachi|idol|vt|cre|chu|neta|sei|hage)$/.test(e.k))o.k=e.k}else if(k==='kind'){o.kind=e.kind==='direct'?'direct':'battle'}else if(k==='why'){o.why=e.why==='life'?'life':''}else if(['h','free','same','scr'].includes(k))o[k]=!!e[k];else if(k==='to'&&e.to==null)o.to=null;else o[k]=number(e[k])}return o})}
function cleanFrames(frames){return(Array.isArray(frames)?frames:[]).slice(-16).filter(f=>f&&f.state&&Array.isArray(f.state.players)&&f.state.players.length===2&&f.state.players.every(p=>p&&card(p.leadId))&&typeof f.key==='string').map(f=>({key:f.key.slice(0,100),state:cleanState(f.state),events:cleanEvents(f.events)}))}
function makeRecord(state,d,first,seq,updated,frames,coins){return{v:2,coins:cleanCoins(coins),frames:cleanFrames(frames),a:d.a,b:d.b,an:String(d.an||'プレイヤーA').slice(0,40),bn:String(d.bn||'プレイヤーB').slice(0,40),first:first==='b'?'b':'a',seq:number(seq,100000),started:number(d.t,Number.MAX_SAFE_INTEGER),updated:number(updated,Number.MAX_SAFE_INTEGER),state:cleanState(state)}}
const api={publicState,cleanState,cleanEvents,cleanFrames,cleanCoins,makeRecord};root.TCGSpectator=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
